### ISSUE TITLE
React Native

### ISSUE THREAD

**Issue by sljavi** [laplatajs/charlas#1]
Getting started - demo app

**Comment by dpaez** [comment]
@pablood85 podría estar dando esta charla en octubre.

**Comment by pablood85** [comment]
Si claro, estaría bueno. Podemos dar una intro a React Native, explicar qué es, cuáles son las diferencias con otras herramientas como phonegap y mostrar como hacer alguna app sencilla.

**Comment by dpaez** [comment]
Charla confirmada para la meetup de Octubre de la mano de @pablood85 :cool:

**Comment by dpaez** [comment]
@pablood85 pasanos el nombre de la charla y tu usuario de twitter.

**Comment by pablood85** [comment]
La charla se va a llamar "Descubriendo React Native". @pablood es mi usuario de Twitter.
