### ISSUE TITLE
Angular 2 & firebase

### ISSUE THREAD

**Issue by jorgeucano** [laplatajs/charlas#11]
@jorgeucano

**Comment by tinchoz49** [comment]
@jorgeucano te parece meter la charlita en la meetup de Septiembre? @elmasse @dpaez que opinan?

**Comment by elmasse** [comment]
En principio estaríamos pensando para la semana del 20/9. Apuntamos al Jueves 22.

**Comment by jorgeucano** [comment]
por mi esta perfecto!

**Comment by tinchoz49** [comment]
bueno listo entonces! confirmamos la charla!

**Comment by elmasse** [comment]
@jorgeucano cuando puedas pasanos el titulo de charla e info tuya (twitter, nombre, etc) así armamos el flyer. Quedo confirmada para el 22/9 a las 19hs.

**Comment by jorgeucano** [comment]
Aca va la info

https://docs.google.com/document/d/1RhAc4LNVLLjY2O_7GVHVzUCuqIVnH-EWO-JRWxPzOGE/edit?usp=sharing
