### ISSUE TITLE
GraphQL

### ISSUE THREAD

**Issue by estebanprimost** [laplatajs/charlas#12]
- Intro a GraphQL.
- Pros/Cons.
- Ejemplos con JS. 
- vs REST.
- Etc.

**Comment by dpaez** [comment]
Felicitaciones @estebanprimost vamos con tu propuesta. Vas a ser speaker de la meetup de octubre  :tada: :cool:

**Comment by dpaez** [comment]
@estebanprimost pasanos el nombre de la charla y tu usuario de twitter

**Comment by estebanprimost** [comment]
Título: **WTF con GraphQL? - Intro + Experiencia**. Opción 2: **Introducción a GraphQL**. La que les dé mas bronca.

Tw: [@estebanprimost](https://twitter.com/estebanprimost)
