### ISSUE TITLE
WebVR con AFrame.

### ISSUE THREAD

**Issue by tinchoforever** [laplatajs/charlas#14]
Les voy a contar como hacer Aframe marcó mi ultimo año y como puede hacerlos construir experiencias solidas y grandes de WEB VR aprendiendo nuevas reglas pero aplicando todo lo que ya saben de JS / HTML.
Vamos a pasar por Miradas360, Sectadelgatillo.com.ar, Belisario y otras.

**Comment by FerreroFacundo** [comment]
vamooooo!!!!

**Comment by tinchoz49** [comment]
yo creo que esta charla ya la podemos dejar ultra confirmada para diciembre! :clap:

**Comment by tinchoz49** [comment]
@tinchoforever pasame el titulo oficial de la charla o confirmame si es `WebVR con AFrame` y de descripción meto esto? (para el flyer :D)

> Les voy a contar como hacer Aframe marcó mi ultimo año y como puede hacerlos construir experiencias solidas y grandes de WEB VR aprendiendo nuevas reglas pero aplicando todo lo que ya saben de JS / HTML.
Vamos a pasar por Miradas360, Sectadelgatillo.com.ar, Belisario y otras.

**Comment by dpaez** [comment]
ping @tinchoforever

**Comment by tinchoz49** [comment]
gracias @tinchoforever !!! so groso!
