### ISSUE TITLE
JSON Web Tokens

### ISSUE THREAD

**Issue by galberola** [laplatajs/charlas#18]
## JSON Web Tokens

La idea de la charla es dar una introducción al mundo de JWT.

- Por qué JWT?
- Algunos de los beneficios de usar JWT
- Cómo está compuesto un token
- Encriptación simétrica vs asimétrica
- Como utilizarlos en infraestructuras de mas de un servicio
- Buenas prácticas

**Comment by tinchoz49** [comment]
@galberola te copas en dar la charla para mayo?

**Comment by galberola** [comment]
@tinchoz49 Colgue en responder... Mala mia...
Si, por mi parte encantado. Lo único tendríamos que ver el tema fecha. 

Ustedes ya tenían alguna fecha en particular en mente?
Planean hacerla día de semana o fin de semana?

**Comment by tinchoz49** [comment]
genial @galberola ! seria el sabado 27

**Comment by galberola** [comment]
Si, anotame nomás @tinchoz49 para dar la charla ese día :+1:

**Comment by tinchoz49** [comment]
perfecto!! la charla se llama como el issue? (asi ya vamos metiendo en el flyer todo)

**Comment by dpaez** [comment]
@galberola también pasanos tu usuario de twitter (si tenes).

**Comment by dpaez** [comment]
Y gracias por compartir tu conocimiento! :clap: :+1:

**Comment by tinchoz49** [comment]
gracias por la buena onda @galberola ! voy cerrando el issue
