### ISSUE TITLE
Extensiones nativas en NodeJS: como y porqué

### ISSUE THREAD

**Issue by betomoretti** [laplatajs/charlas#25]
La idea es contar de manera introductoria algunos conceptos relacionados a la implementación de extensiones nativas para NodeJS, algunos beneficios, mencionar a librerías, y mostrar algún que otro demo.

**Comment by dpaez** [comment]
Genial beto, you are in.

:+1: https://gph.is/XLs4YX

Pasanos:
- [x] twitter handle

**Comment by marianomoretti** [comment]
:clap: @btomoretti

**Comment by betomoretti** [comment]
:clap: @btomoretti
