### ISSUE TITLE
Full Stack GraphQL

### ISSUE THREAD

**Issue by marcosfede** [laplatajs/charlas#34]
Buenas! Me llamo Fede y soy un asistente regular a las meetups aunque siempre de oyente. Me gustaría devolver a la comunidad dando una charla sobre GraphQL y como arrancar tanto desde el front como el backend.

Ya di charlas similares en la empresa donde trabajo (Celerative) y en meetups de laplata.py, pueden ver los slides [acá](https://slides.com/federicomarcos/introduccion-a-2) aunque seguramente sufra cambios

La idea es hacer una introducción a GraphQL, cuales son las motivaciones y problemas que viene a resolver, algunas de las ventajas y desventajas y como arrancar con esta tecnología usando JS, tanto desde el front como desde el backend

La siguiente lista de topics es provisoria y me gustaría recibir feedback sobre que temas agregar/dejar de lado

## Topics
- Introducción, motivaciones
- Apollo 
- GraphQL Yoga
- TypeORM
- DataLoader
- Prisma.io
- Postgraphile

Duración: 60 minutos
Complejidad: Intermedia. No es necesario tener conocimientos previos de GraphQL, pero si los tenés hay algunos tips interesantes.
Posibles fechas: Fines de noviembre en adelante
Contacto: me pueden encontrar como `@fede.m` en el slack

**Comment by dpaez** [comment]
Hola @marcosfede 👋 Muchas gracias por la propuesta de charla!!! 💟 
Suena muy interesante la propuesta, lo primero que veo es que deberiamos ajustarla o enfocarla en algún sub-topico por el tema del tiempo, 60 min para una charla de laplatajs es mucho tiempo, habria que reducirla a la mitad max, es decir 30min. Esa es una opción y me parece super interesante hacer foco en algun aspecto de GQL. En el pasado hemos tenido otra charla de GQL, que mostraba muchas de las novedades que introduce.

La otra opción si no queres reducirla, es transformarla en workshop. Esto puede requerir un poco mas de trabajo de tu lado para adecuar los ejercicios que se iran resolviendo, en el caso de un workshop podemos hacerlo de entre 2 y 3hs. Ya tenemos un workshop propuesto para noviembre y planeamos meetup para diciembre por lo que creo, a priori, esto podria pasar al año que viene. Pero mantengamos la conversación y nuevamente **muchas gracias por animarte a proponer una charla**!

**Comment by marcosfede** [comment]
@dpaez No hay problema! Puedo acortarla, hacerla de 30 min aproximadamente. En ese caso la enfocaría más en el backend, y contaría un poco de cuales son las opciones que existen actualmente.

**Comment by betomoretti** [comment]
Hola @marcosfede!! El 8 de diciembre estamos organizando LaPlataJS Day, y queda un espacio disponible de 15hs a 15:30hs para dar una charla. Tenes ganas de participar presentando esta charla? :)

Te dejo el link del evento para que tengas mas info: https://www.eventbrite.com.ar/e/laplatajs-day-tickets-52888758701

Gracias!
